services:
  - type: web
    name: chatmate
    env: node
    plan: free
    buildCommand: npm ci && npm ci --prefix frontend && npm run build --prefix frontend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
